### ISSUE TITLE
Can't import

### ISSUE THREAD

**Issue by jabbermacy** [sclebo05/KobraNeoProfiles#1]
I'm new, but not stupid, been printing for 7 years :-)  help meh pls... 

![image](https://user-images.githubusercontent.com/49337913/211411529-b75340b5-6355-4ace-9cce-331401935c6d.png)

**Comment by sclebo05** [comment]
Make sure you're using cura 5.3 alpha. Also, you seem to have a fdm printer default, I created the any cubic cobra device first, then imported these profiles.

**Comment by jabbermacy** [comment]
Ah that's it, thanks sir!!
