### ISSUE TITLE
Retraction setting reverted to 6mm

### ISSUE THREAD

**Issue by DanPerovich** [sclebo05/KobraNeoProfiles#11]
Were the retraction settings reverted from 1mm (Jan. pull) back to 6mm in the Cura profiles?  I just loaded the .2mm and .2mm fast profiles into Cura and noticed they are 6mm when I thought it was said that 6mm is way to much for a direct drive.

Total newb here....so I could be mistaken.

**Comment by DanPerovich** [comment]
Nevermind.  Appears to be a Cura bug.  In the Preferences --> Profile page, when selecting the imported AKNeo... profiles still show a 6mm retraction distance.  However, when you use the profile in the main interface, it reflects the 1 mm retraction distance. 

![image](https://github.com/sclebo05/KobraNeoProfiles/assets/6865659/d485cff5-c6d9-4f54-b16e-d1053b2e7dab)

**Comment by sclebo05** [comment]
That seems odd.  I just verified by 5.4 install, I show it as 1mm in the Print Settings panel, and yep, it's 6mm on the profile page. Just did a quick test print, I think the 1mm is the current setting.  Nice sleuthing to point this out.
