### ISSUE TITLE
Import Profile Cura error

### ISSUE THREAD

**Issue by angeloken** [sclebo05/KobraNeoProfiles#12]
![Screenshot 2023-08-07 140805](https://github.com/sclebo05/KobraNeoProfiles/assets/58063425/de8eb068-a4dc-47e5-b5db-4713f698d7dc)

i got an error when i want to import the profile, how to solve this? (my cura already latest version 5.4)

**Comment by sclebo05** [comment]
Try creating a Kobra first, check out the installation instructions https://github.com/sclebo05/KobraNeoProfiles/blob/main/Install.md

**Comment by angeloken** [comment]
![Screenshot 2023-08-07 143825](https://github.com/sclebo05/KobraNeoProfiles/assets/58063425/d0f95aba-3173-4d96-9add-cd0f1fe12a57)
i already have one

**Comment by sclebo05** [comment]
No, I don't think that you do. Run the wizard and create a Anycubic Kobra (there is no Neo) from the pre populated options. Creating an 'fdmprinter' from scratch and importing will not work.

**Comment by angeloken** [comment]
ahh i see because i used the custom printer, okay thanks a lot

**Comment by sclebo05** [comment]
Glad to help. Happy printing

**Comment by kprasadvnsi** [comment]
I have the same problem and I not sure what I am doing wrong. 

![Screenshot from 2023-11-20 13-46-56](https://github.com/sclebo05/KobraNeoProfiles/assets/3696543/7c42c5aa-09b2-40e5-ba87-0835404c0e05)

**Comment by sclebo05** [comment]
Need to create a Kobra printer first. Instructions here https://github.com/sclebo05/KobraNeoProfiles/blob/main/Install.md

**Comment by kprasadvnsi** [comment]
> Need to create a Kobra printer first. Instructions here https://github.com/sclebo05/KobraNeoProfiles/blob/main/Install.md

I did follow this installation guide. I fixed it by editing the profile file and replacing quality_type=pla to quality_type=draft.
