### ISSUE TITLE
Problem when import profile in Cura

### ISSUE THREAD

**Issue by Mastercard123456789** [sclebo05/KobraNeoProfiles#15]
Hi,
when i try to import any profile in cura i've got the error:
"Quality type 'pla' is not compatibe with the current active machine definition 'fdmprinter'"...
How can i solve?

**Comment by sclebo05** [comment]
Please follow the installation directions, need to create a Kobra first.

**Comment by wiwaszko** [comment]
Change:
quality_type = pla
to
quality_type = draft

**Comment by Mastercard123456789** [comment]
Thanks, it work!

**Comment by alehano** [comment]
> Change: quality_type = pla to quality_type = draft

Where can I do this?

**Comment by sclebo05** [comment]
Some users reported this tweak in the cura profile

**Comment by alehano** [comment]
> Some users reported this tweak in the cura profile

Unfortunately I have the same issue and no idea where to change "quality_type". Can't see this option in the profile page.

**Comment by sclebo05** [comment]
lines 8 and 21 in the .curaprofile file.

It may also be possible to open the .3mf profile file and have everything imported for you.  Be sure to check the instructions on the Install page.

**Comment by alehano** [comment]
> lines 8 and 21 in the .curaprofile file.
> 
> It may also be possible to open the .3mf profile file and have everything imported for you. Be sure to check the instructions on the Install page.

It's seems it's not plain text, cause it has weird symbols. And after saving the file, there is another error while importing.

<img width="632" alt="Screenshot 2023-12-03 at 14 25 50" src="https://github.com/sclebo05/KobraNeoProfiles/assets/1269330/a2cbf874-ee4b-437f-a944-7320fa5e35cf">
