### ISSUE TITLE
Start gcode not compatible with power loss recovery

### ISSUE THREAD

**Issue by evan** [sclebo05/KobraNeoProfiles#2]
Thanks for your profiles and gcode; they are helping me get started with this printer. I noticed the start code is not compatible with power loss recovery:

How to reproduce:

  - ensure power loss recovery is on
  - print benchy
  - power cycle printer half-way through
  - choose resume on printer
  - extruder tries to print the start line again, knocks the half-done benchy off the plate, and resumes printing at the correct layer but at the wrong height (I think)

**Comment by sclebo05** [comment]
I have a different behavior, the print did restart but in the middle of Layer1.  Investigating the SD card, there is no recovery file being created.  Firmware issue?  I'm running 1.3.3.

**Comment by evan** [comment]
I have the stock 1.2.9 that my printer came with, even though 1.2.8 is available on the Anycubic site as the "latest". Do I need to upgrade to the community 1.3.3 build?

**Comment by sclebo05** [comment]
I can't answer that definitively, I'm looking through the C++ in 1.3.3 that was shared on GitHub.  I'm testing with it enabled AND an M500 code.  Will know more in 20 minutes.

**Comment by sclebo05** [comment]
On my printer, it attempts to restart but I agree, at the wrong z height.  In fact, the z height was so far off it scraped through the entire print to the bed, luckily no permanant scratches.  The Marlin firmware documentation states that the SD card OR the eeprom should be storing the resume information, but I haven't found any.  Leaving this bug open, and until this gets sorted, I'm explicitly turning power-loss recovery OFF.  Making a note in the Readme. 

 https://marlinfw.org/docs/gcode/M413.html 

![IMG_20230119_084921699_HDR](https://user-images.githubusercontent.com/39742566/213463866-655ba73e-94f2-41cd-a57c-2aea76dc8876.jpg)

**Comment by 1coderookie** [comment]
Hey Josh, I just sent you an email but just in case it gets stuck in your spam folder:
I don't wanna crash the discussion here in this issue, but as you're talking about the official FW1.3.3 - could you maybe be so kind and upload the firmware.bin of the 1.3.3 to your repo also (or send it to me via email directly)? That would be GREAT as I have no clue how to generate it and it maybe also could help out @evan and others who have the same problem..

**Comment by 1coderookie** [comment]
Thank you SO much!

**Comment by sclebo05** [comment]
I've done testing with and without power loss recovery, and I see a difference when enabling the recovery.  Leaving this feature disabled and made a note in the readme.md file.
