### ISSUE TITLE
Retraction distance is too high

### ISSUE THREAD

**Issue by evan** [sclebo05/KobraNeoProfiles#3]
I've had better results with 1mm than 6mm.

**Comment by sclebo05** [comment]
Definitely helps again.  I'm going with 2mm after a few tests. Thanks for the input!

![benchyfever](https://user-images.githubusercontent.com/39742566/213528658-f51b2444-a047-4789-9ab5-50a9d04ab866.jpg)

**Comment by evan** [comment]
I saw the commit for 1mm retraction distance. I found this https://www.thingiverse.com/thing:2975429 to be a very good test. I have only printed it a few times but I think I got the best results with 0.5mm for PLA. 1mm was also quite good, but had more oozing on the lower overhangs.
