### ISSUE TITLE
Print sometimes starts at too high a Z position

### ISSUE THREAD

**Issue by evan** [sclebo05/KobraNeoProfiles#4]
I'm unsure if this is related to the start G code or not, but every 5 or 6 prints the printer will not home correctly and begin printing 5mm-10mm off the bed. If it's starting at the wrong X and Y position I wouldn't really notice I guess. Wondered if you have seen this issue.

**Comment by sclebo05** [comment]
Just curious - were able to find the source of this issue? I haven't experienced this on my unit with firmwares 1.2.9 or 1.3.3.  Haven't run into it with any profiles, using different slicers.  Are you still having this issue?

**Comment by evan** [comment]
I updated to a community build of 1.3.3 and haven't noticed the issue since, but I haven't printed much recently either.

**Comment by sclebo05** [comment]
Looks like Evan figured this out, good luck to him.
