### ISSUE TITLE
Provide profiles for Cura 5.2.2 as well while Cura 5.3.0 Beta is not available

### ISSUE THREAD

**Issue by ghost** [sclebo05/KobraNeoProfiles#6]
Hi, thanks for your work but Cura 5.3.0 Beta is not available on Cura Github Release page, only 5.2.2. So can you provide the profiles for 5.2.2 as well while 5.3.0 is not available and importing fails with. Thank you

**Comment by sclebo05** [comment]
Try expanding 'Assets' under the 5.3.0 section of the release page: [https://github.com/Ultimaker/Cura/releases](https://github.com/Ultimaker/Cura/releases) .  

Sticking with 5.3, as it has a base Kobra profile. The point releases are not compatible, so looking forward.

**Comment by ghost** [comment]
Ahh, thanks. Never saw not expanded Assets before. Thought this is default. Many thanks :)
