### ISSUE TITLE
SuperSlicer profile can't be imported: '=' character not found in line at line 8

### ISSUE THREAD

**Issue by 1coderookie** [sclebo05/KobraNeoProfiles#7]
Hi,
I tried to import the SuperSlicer config but it fails with an error message. Not sure if I may did something wrong, so I tried both possibilities:

1) File -> Import -> Import Config
results in 
```
SuperSlicer has encountered and error  
Failed loading the Config Bundle "": '=' character not found in line at line 8
``` 
![Bildschirmfoto von 2023-02-26 09-18-58](https://user-images.githubusercontent.com/25869362/221399794-be33e1c4-257a-4416-aec5-0908dd7a5b33.png)

2) File -> Import -> Import Config Bundle
results in 
``` 
SuperSlicer has encountered and error  
Failed loading config bundle "/path/SS_AKNeo.ini"  
Error: "'=' character not found in line" at line 8  
```
(image same like above but with the path and filename as mentioned in the codeblock).

**Comment by sclebo05** [comment]
I'll try to recreate.  What version of SS are you running?

**Comment by 1coderookie** [comment]
Great, thanks. It's SuperSlicer 2.5.59.0 (for Ubuntu 18.04 gtk2 as an AppImage).

**Comment by sclebo05** [comment]
Ha!  You had me chasing my tail on that one.  Make sure you download the 'raw' version of the file.  I did a 'save link' in my browser and it pulled an HTML version of the file and caused the error. Quickest way to check is with 'head SS_AKNeo.ini' .  you should see config and not html!

If you want to pull the files from the Linux cli, do the GitHub thing, and 'git clone https://github.com/sclebo05/KobraNeoProfiles.git'  to pull down the files.

or the dirty way is 'wget https://raw.githubusercontent.com/sclebo05/KobraNeoProfiles/main/SuperSlicerProfiles/SS_AKNeo.ini' to pull just one.

Did a successful import of the file with the Ubuntu version above. Once imported, use the gear icon and save the filament, printer, print settings.

**Comment by 1coderookie** [comment]
Oh my - you're absolutely right, I did right-click save it this time.. I'm really sorry - I'm using GH since many years and I don't even remember when this I did this mistake the last time, I must have been asleep :flushed:

**Comment by sclebo05** [comment]
Closing issue, just some confusion with code download.
